# Site settings
title: Fozz Games
description: Games created by Fozz
baseurl: "/FozzGames" # Leave empty unless your site is hosted in a subdirectory (e.g., /blog)
url: "https://EliBarton.github.io/FozzGames" # Your site's URL

include:
  - _includes
  - game_files

# If you're using GitHub Pages with a custom domain
# (remove this section if you're not using a custom domain)
#domain: "www.yourcustomdomain.com"

